services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    ports:
      - 1433:1433
    volumes:
      - mssql:/var/opt/mssql
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD:?}"

  back-office:
    build:
      context: .
      dockerfile: Back-office/dockerfile
    ports:
      - "${BACK_OFFICE_PORT:?}:5000"
    environment:
      - RUNNING_IN_DOCKER=true
    env_file:
      - .env
    volumes:
      - backofficekeys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - mssql
      - databaseapi

  webapp:
    build:
      context: .
      dockerfile: WebApp/dockerfile
    ports:
      - "${WEB_APP_PORT:?}:5000"
    environment:
      - RUNNING_IN_DOCKER=true
    env_file:
      - .env
    volumes:
      - webappkeys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - mssql
      - databaseapi

  databaseapi:
    build:
      context: .
      dockerfile: DatabaseApi/dockerfile
    ports:
      - "${DATABASE_API_PORT:?}:5000"
    environment:
      - RUNNING_IN_DOCKER=true
    env_file:
      - .env
    volumes:
      - databaseapikeys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - mssql

volumes:
  mssql:
  backofficekeys:
  webappkeys:
  databaseapikeys:
