<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Back_office</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\ViewModels\**" />
    <Compile Remove="wwwroot\images\**" />
    <Content Remove="Models\ViewModels\**" />
    <Content Remove="wwwroot\images\**" />
    <EmbeddedResource Remove="Models\ViewModels\**" />
    <EmbeddedResource Remove="wwwroot\images\**" />
    <None Remove="Models\ViewModels\**" />
    <None Remove="wwwroot\images\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedClassLibrary\SharedClassLibrary.csproj" />
  </ItemGroup>

</Project>
