FROM dhi.io/dotnet:10-sdk

WORKDIR /app

COPY Back-office/ Back-office/
COPY SharedClassLibrary/ SharedClassLibrary/

WORKDIR /app/Back-office

RUN dotnet restore && dotnet publish -c Release -o out

CMD ["dotnet", "out/Back-office.dll"]

EXPOSE 5000
