FROM dhi.io/dotnet:10-sdk

WORKDIR /app

COPY Back-office/ Back-office/
COPY SharedClassLibrary/ SharedClassLibrary/

WORKDIR /app/Back-office

RUN dotnet restore

CMD ["dotnet", "watch", "run"]

EXPOSE 5000
