FROM dhi.io/dotnet:10-sdk

WORKDIR /app

COPY DatabaseApi/ DatabaseApi/
COPY SharedClassLibrary/ SharedClassLibrary/

WORKDIR /app/DatabaseApi

RUN dotnet restore

CMD ["dotnet", "watch", "run"]

EXPOSE 5000
