FROM dhi.io/dotnet:10-sdk

WORKDIR /app

COPY DatabaseApi/ DatabaseApi/
COPY SharedClassLibrary/ SharedClassLibrary/

WORKDIR /app/DatabaseApi

RUN dotnet restore && dotnet publish -c Release -o out

CMD ["dotnet", "out/DatabaseApi.dll"]

EXPOSE 5000
