// <auto-generated />
using System;
using DatabaseApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260320151043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseApi.Models.Event", b =>
                {
                    b.Property<int>("idEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEvent"));

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("accentColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("logoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mainColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEvent");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DatabaseApi.Models.Room", b =>
                {
                    b.Property<int>("idRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRoom"));

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idEvent")
                        .HasColumnType("int");

                    b.Property<string>("roomLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRoom");

                    b.HasIndex("idEvent");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DatabaseApi.Models.Session", b =>
                {
                    b.Property<int>("idSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSession"));

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEvent")
                        .HasColumnType("int");

                    b.Property<int>("idRoom")
                        .HasColumnType("int");

                    b.Property<bool>("plenary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSession");

                    b.HasIndex("idEvent");

                    b.HasIndex("idRoom");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DatabaseApi.Models.Speaker", b =>
                {
                    b.Property<int>("idSpeaker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSpeaker"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSpeaker");

                    b.ToTable("Speakers");
                });

            modelBuilder.Entity("DatabaseApi.Models.Tag", b =>
                {
                    b.Property<string>("title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("idEvent")
                        .HasColumnType("int");

                    b.Property<string>("colorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("title", "idEvent");

                    b.HasIndex("idEvent");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DatabaseApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DatabaseApi.Models.User_has_Session", b =>
                {
                    b.Property<string>("idUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("idSession")
                        .HasColumnType("int");

                    b.Property<bool>("inWaitingList")
                        .HasColumnType("bit");

                    b.Property<DateTime>("joinedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("idUser", "idSession");

                    b.HasIndex("idSession");

                    b.ToTable("User_has_Sessions");
                });

            modelBuilder.Entity("Session_has_Speaker", b =>
                {
                    b.Property<int>("SessionsidSession")
                        .HasColumnType("int");

                    b.Property<int>("SpeakersidSpeaker")
                        .HasColumnType("int");

                    b.HasKey("SessionsidSession", "SpeakersidSpeaker");

                    b.HasIndex("SpeakersidSpeaker");

                    b.ToTable("Session_has_Speaker");
                });

            modelBuilder.Entity("Session_has_Tag", b =>
                {
                    b.Property<int>("SessionsidSession")
                        .HasColumnType("int");

                    b.Property<string>("Tagstitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TagsidEvent")
                        .HasColumnType("int");

                    b.HasKey("SessionsidSession", "Tagstitle", "TagsidEvent");

                    b.HasIndex("Tagstitle", "TagsidEvent");

                    b.ToTable("Session_has_Tag");
                });

            modelBuilder.Entity("User_has_Event", b =>
                {
                    b.Property<int>("EventsidEvent")
                        .HasColumnType("int");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EventsidEvent", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("User_has_Event");
                });

            modelBuilder.Entity("DatabaseApi.Models.Room", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", "Event")
                        .WithMany("Rooms")
                        .HasForeignKey("idEvent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DatabaseApi.Models.Session", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("idEvent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("idRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DatabaseApi.Models.Tag", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", "Event")
                        .WithMany("Tags")
                        .HasForeignKey("idEvent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DatabaseApi.Models.User_has_Session", b =>
                {
                    b.HasOne("DatabaseApi.Models.Session", "Session")
                        .WithMany("RegisteredUsers")
                        .HasForeignKey("idSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.User", "User")
                        .WithMany("RegisteredSessions")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Session_has_Speaker", b =>
                {
                    b.HasOne("DatabaseApi.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionsidSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.Speaker", null)
                        .WithMany()
                        .HasForeignKey("SpeakersidSpeaker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Session_has_Tag", b =>
                {
                    b.HasOne("DatabaseApi.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionsidSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("Tagstitle", "TagsidEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("User_has_Event", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsidEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseApi.Models.Event", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DatabaseApi.Models.Room", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DatabaseApi.Models.Session", b =>
                {
                    b.Navigation("RegisteredUsers");
                });

            modelBuilder.Entity("DatabaseApi.Models.User", b =>
                {
                    b.Navigation("RegisteredSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
