// <auto-generated />
using System;
using DatabaseApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseApi.Models.Event", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvent"));

                    b.Property<string>("AccentColorHex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainColorHex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEvent");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            IdEvent = 1,
                            AccentColorHex = "#B0B0B0",
                            Description = "Hier zal besproken worden wat er allemaal gemaakt moet worden voor de beste event calender ooit.",
                            EndDate = new DateTime(2026, 10, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "'s-Hertogenbosch",
                            LogoPath = "",
                            MainColorHex = "#D9D9D9",
                            StartDate = new DateTime(2026, 10, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "iO Event Connect"
                        });
                });

            modelBuilder.Entity("DatabaseApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DatabaseApi.Models.Room", b =>
                {
                    b.Property<int>("IdRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoom"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<string>("RoomLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdRoom");

                    b.HasIndex("IdEvent", "RoomLabel")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            IdRoom = 1,
                            Capacity = 100,
                            Description = "Grote conferentiezaal.",
                            IdEvent = 1,
                            RoomLabel = "Hoofdzaal"
                        },
                        new
                        {
                            IdRoom = 2,
                            Capacity = 20,
                            Description = "Grote meeting zaal.",
                            IdEvent = 1,
                            RoomLabel = "Kamer 1"
                        },
                        new
                        {
                            IdRoom = 3,
                            Capacity = 2,
                            Description = "Kleine meeting zaal.",
                            IdEvent = 1,
                            RoomLabel = "Kamer 2"
                        });
                });

            modelBuilder.Entity("DatabaseApi.Models.Session", b =>
                {
                    b.Property<int>("IdSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSession"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<bool>("Plenary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSession");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdRoom");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            IdSession = 1,
                            EndTime = new DateTime(2026, 10, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdEvent = 1,
                            IdRoom = 1,
                            Plenary = true,
                            StartTime = new DateTime(2026, 10, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bespreking algemene eisen en wensen."
                        },
                        new
                        {
                            IdSession = 2,
                            Capacity = 20,
                            EndTime = new DateTime(2026, 10, 10, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEvent = 1,
                            IdRoom = 2,
                            Plenary = false,
                            StartTime = new DateTime(2026, 10, 10, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Database architectuur."
                        },
                        new
                        {
                            IdSession = 3,
                            Capacity = 2,
                            EndTime = new DateTime(2026, 10, 10, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IdEvent = 1,
                            IdRoom = 3,
                            Plenary = false,
                            StartTime = new DateTime(2026, 10, 10, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Routing architectuur."
                        });
                });

            modelBuilder.Entity("DatabaseApi.Models.Speaker", b =>
                {
                    b.Property<int>("IdSpeaker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSpeaker"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSpeaker");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            IdSpeaker = 1,
                            FirstName = "Jan",
                            ImgPath = "",
                            LastName = "Smit",
                            description = "Expert in C# en Cloud."
                        },
                        new
                        {
                            IdSpeaker = 2,
                            FirstName = "John",
                            ImgPath = "",
                            LastName = "Doe",
                            description = "Expert in Databases en networking."
                        });
                });

            modelBuilder.Entity("DatabaseApi.Models.Tag", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title", "IdEvent");

                    b.HasIndex("IdEvent");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Title = "Plenaire sessie",
                            IdEvent = 1,
                            ColorHex = "#D5B82C"
                        },
                        new
                        {
                            Title = "Technology",
                            IdEvent = 1,
                            ColorHex = "#2CCFD5"
                        });
                });

            modelBuilder.Entity("DatabaseApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Email = "jan.smit@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JAN.SMIT@EXAMPLE.COM",
                            NormalizedUserName = "JAN.SMIT@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE9XsCMDkXMdTDw5BcaJ7teKfgRDJpxSUt6WF2/3BaCbJaJkCFImPUBAKfygEXtbVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC-STAMP-001",
                            TwoFactorEnabled = false,
                            UserName = "jan.smit@example.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE9XsCMDkXMdTDw5BcaJ7teKfgRDJpxSUt6WF2/3BaCbJaJkCFImPUBAKfygEXtbVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC-STAMP-002",
                            TwoFactorEnabled = false,
                            UserName = "john.doe@example.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            Email = "jane.smith@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "JANE.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE9XsCMDkXMdTDw5BcaJ7teKfgRDJpxSUt6WF2/3BaCbJaJkCFImPUBAKfygEXtbVg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC-STAMP-003",
                            TwoFactorEnabled = false,
                            UserName = "jane.smith@example.com"
                        });
                });

            modelBuilder.Entity("DatabaseApi.Models.User_has_Session", b =>
                {
                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdSession")
                        .HasColumnType("int");

                    b.Property<bool>("InWaitingList")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUser", "IdSession");

                    b.HasIndex("IdSession");

                    b.ToTable("User_has_Sessions");

                    b.HasData(
                        new
                        {
                            IdUser = "1",
                            IdSession = 1,
                            InWaitingList = false,
                            JoinedDate = new DateTime(2026, 10, 10, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdUser = "1",
                            IdSession = 3,
                            InWaitingList = false,
                            JoinedDate = new DateTime(2026, 10, 10, 8, 5, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdUser = "2",
                            IdSession = 3,
                            InWaitingList = false,
                            JoinedDate = new DateTime(2026, 10, 10, 10, 10, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Session_has_Speaker", b =>
                {
                    b.Property<int>("SessionsIdSession")
                        .HasColumnType("int");

                    b.Property<int>("SpeakersIdSpeaker")
                        .HasColumnType("int");

                    b.HasKey("SessionsIdSession", "SpeakersIdSpeaker");

                    b.HasIndex("SpeakersIdSpeaker");

                    b.ToTable("Session_has_Speaker");

                    b.HasData(
                        new
                        {
                            SessionsIdSession = 1,
                            SpeakersIdSpeaker = 1
                        });
                });

            modelBuilder.Entity("Session_has_Tag", b =>
                {
                    b.Property<int>("SessionsIdSession")
                        .HasColumnType("int");

                    b.Property<string>("TagsTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TagsIdEvent")
                        .HasColumnType("int");

                    b.HasKey("SessionsIdSession", "TagsTitle", "TagsIdEvent");

                    b.HasIndex("TagsTitle", "TagsIdEvent");

                    b.ToTable("Session_has_Tag");

                    b.HasData(
                        new
                        {
                            SessionsIdSession = 1,
                            TagsTitle = "Plenaire sessie",
                            TagsIdEvent = 1
                        },
                        new
                        {
                            SessionsIdSession = 1,
                            TagsTitle = "Technology",
                            TagsIdEvent = 1
                        });
                });

            modelBuilder.Entity("User_has_Event", b =>
                {
                    b.Property<int>("EventsIdEvent")
                        .HasColumnType("int");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EventsIdEvent", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("User_has_Event");

                    b.HasData(
                        new
                        {
                            EventsIdEvent = 1,
                            UsersId = "1"
                        },
                        new
                        {
                            EventsIdEvent = 1,
                            UsersId = "2"
                        },
                        new
                        {
                            EventsIdEvent = 1,
                            UsersId = "3"
                        });
                });

            modelBuilder.Entity("DatabaseApi.Models.Room", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", "Event")
                        .WithMany("Rooms")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DatabaseApi.Models.Session", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DatabaseApi.Models.Tag", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", "Event")
                        .WithMany("Tags")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DatabaseApi.Models.User_has_Session", b =>
                {
                    b.HasOne("DatabaseApi.Models.Session", "Session")
                        .WithMany("RegisteredUsers")
                        .HasForeignKey("IdSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.User", "User")
                        .WithMany("RegisteredSessions")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DatabaseApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DatabaseApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DatabaseApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Session_has_Speaker", b =>
                {
                    b.HasOne("DatabaseApi.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionsIdSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.Speaker", null)
                        .WithMany()
                        .HasForeignKey("SpeakersIdSpeaker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Session_has_Tag", b =>
                {
                    b.HasOne("DatabaseApi.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionsIdSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTitle", "TagsIdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("User_has_Event", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsIdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseApi.Models.Event", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DatabaseApi.Models.Room", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DatabaseApi.Models.Session", b =>
                {
                    b.Navigation("RegisteredUsers");
                });

            modelBuilder.Entity("DatabaseApi.Models.User", b =>
                {
                    b.Navigation("RegisteredSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
