// <auto-generated />
using System;
using DatabaseApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseApi.Models.Event", b =>
                {
                    b.Property<int>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvent"));

                    b.Property<string>("AccentColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEvent");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DatabaseApi.Models.Room", b =>
                {
                    b.Property<int>("IdRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoom"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<string>("RoomLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRoom");

                    b.HasIndex("IdEvent");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DatabaseApi.Models.Session", b =>
                {
                    b.Property<int>("IdSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSession"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<bool>("Plenary")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSession");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdRoom");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DatabaseApi.Models.Speaker", b =>
                {
                    b.Property<int>("IdSpeaker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSpeaker"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSpeaker");

                    b.ToTable("Speakers");
                });

            modelBuilder.Entity("DatabaseApi.Models.Tag", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title", "IdEvent");

                    b.HasIndex("IdEvent");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DatabaseApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DatabaseApi.Models.User_has_Session", b =>
                {
                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdSession")
                        .HasColumnType("int");

                    b.Property<bool>("InWaitingList")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUser", "IdSession");

                    b.HasIndex("IdSession");

                    b.ToTable("User_has_Sessions");
                });

            modelBuilder.Entity("Session_has_Speaker", b =>
                {
                    b.Property<int>("SessionsIdSession")
                        .HasColumnType("int");

                    b.Property<int>("SpeakersIdSpeaker")
                        .HasColumnType("int");

                    b.HasKey("SessionsIdSession", "SpeakersIdSpeaker");

                    b.HasIndex("SpeakersIdSpeaker");

                    b.ToTable("Session_has_Speaker");
                });

            modelBuilder.Entity("Session_has_Tag", b =>
                {
                    b.Property<int>("SessionsIdSession")
                        .HasColumnType("int");

                    b.Property<string>("TagsTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TagsIdEvent")
                        .HasColumnType("int");

                    b.HasKey("SessionsIdSession", "TagsTitle", "TagsIdEvent");

                    b.HasIndex("TagsTitle", "TagsIdEvent");

                    b.ToTable("Session_has_Tag");
                });

            modelBuilder.Entity("User_has_Event", b =>
                {
                    b.Property<int>("EventsIdEvent")
                        .HasColumnType("int");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EventsIdEvent", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("User_has_Event");
                });

            modelBuilder.Entity("DatabaseApi.Models.Room", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", "Event")
                        .WithMany("Rooms")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DatabaseApi.Models.Session", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DatabaseApi.Models.Tag", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", "Event")
                        .WithMany("Tags")
                        .HasForeignKey("IdEvent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DatabaseApi.Models.User_has_Session", b =>
                {
                    b.HasOne("DatabaseApi.Models.Session", "Session")
                        .WithMany("RegisteredUsers")
                        .HasForeignKey("IdSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.User", "User")
                        .WithMany("RegisteredSessions")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Session_has_Speaker", b =>
                {
                    b.HasOne("DatabaseApi.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionsIdSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.Speaker", null)
                        .WithMany()
                        .HasForeignKey("SpeakersIdSpeaker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Session_has_Tag", b =>
                {
                    b.HasOne("DatabaseApi.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionsIdSession")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsTitle", "TagsIdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("User_has_Event", b =>
                {
                    b.HasOne("DatabaseApi.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsIdEvent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseApi.Models.Event", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DatabaseApi.Models.Room", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DatabaseApi.Models.Session", b =>
                {
                    b.Navigation("RegisteredUsers");
                });

            modelBuilder.Entity("DatabaseApi.Models.User", b =>
                {
                    b.Navigation("RegisteredSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
