FROM dhi.io/dotnet:10-sdk

WORKDIR /app

COPY WebApp/ WebApp/
COPY SharedClassLibrary/ SharedClassLibrary/

WORKDIR /app/WebApp

RUN dotnet restore && dotnet publish -c Release -o out

CMD ["dotnet", "out/WebApp.dll"]

EXPOSE 5000
